Repository HyPlayer/HyPlayer, pull requests merged in 2022-10, with the labels that each got.

#274 [Feature] 接入Last.FM 音乐记录平台
  HyPlayer/App.xaml.cs
  HyPlayer/Classes/LastFMManager.cs
  HyPlayer/Common.cs
  HyPlayer/Controls/LastFMLoginBox.xaml
  HyPlayer/Controls/LastFMLoginBox.xaml.cs
  HyPlayer/HyPlayControl/HyPlayList.cs
  HyPlayer/HyPlayer.csproj
  HyPlayer/Package.appxmanifest
  HyPlayer/Pages/BasePage.xaml.cs
  HyPlayer/Pages/Settings.xaml
  HyPlayer/Pages/Settings.xaml.cs
  README.md
Labels: enhancement

#277 Playbar支持亚克力效果
  HyPlayer/Classes/Converters.cs
  HyPlayer/Classes/ConvertersDictionary.xaml
  HyPlayer/Common.cs
  HyPlayer/Controls/GroupedSongsList.xaml
  HyPlayer/Controls/PlayBar.xaml
  HyPlayer/Controls/PlayBar.xaml.cs
  HyPlayer/Controls/SongsList.xaml
  HyPlayer/MainPage.xaml
  HyPlayer/MainPage.xaml.cs
  HyPlayer/Pages/BasePage.xaml
  HyPlayer/Pages/Home.xaml
  HyPlayer/Pages/Settings.xaml
  HyPlayer/Resources/Acrylic.xaml
Labels: :增强, ~近期修复, =跟进中, @开发团队

#279 修复由于未判段Null导致崩溃的Bug，修复不能上传文件至音乐云盘的Bug，优化(或负优化)搓碟逻辑
  HyPlayer/Classes/CloudUpload.cs
  HyPlayer/Classes/LastFMManager.cs
  HyPlayer/HyPlayControl/HyPlayList.cs
  HyPlayer/Pages/ExpandedPlayer.xaml
  HyPlayer/Pages/ExpandedPlayer.xaml.cs
  HyPlayer/Pages/LocalMusicPage.xaml
  HyPlayer/Pages/LocalMusicPage.xaml.cs
Labels: :增强, ~近期修复, =跟进中, @开发团队

#281 [PlayBar] 使用Manipulation替换ValueChanged以减小拖动进度条时的CPU占用及降低崩溃几率
  HyPlayer/Controls/PlayBar.xaml
  HyPlayer/Controls/PlayBar.xaml.cs
Labels: ~近期修复, =跟进中, @原作者
