Repository HyPlayer/HyPlayer, pull requests merged in 2023-07, with the labels that each got.

#404 将设置页面迁移CommunityToolkit.Labs.Uwp.SettingsControls
  HyPlayer/HyPlayer.csproj
  HyPlayer/Pages/Settings.xaml
  HyPlayer/Pages/Settings.xaml.cs
Labels: · 增强, =跟进中

#413 播放条背景优化
  HyPlayer/App.xaml
  HyPlayer/Classes/Converters.cs
  HyPlayer/Classes/ConvertersDictionary.xaml
  HyPlayer/Common.cs
  HyPlayer/Controls/CommentsList.xaml
  HyPlayer/Controls/GroupedSongsList.xaml
  HyPlayer/Controls/PlayBar.xaml
  HyPlayer/Controls/PlayBar.xaml.cs
  HyPlayer/Controls/SimpleLinerList.xaml
  HyPlayer/Controls/SongsList.xaml
  HyPlayer/Controls/SongsList.xaml.cs
  HyPlayer/MainPage.xaml
  HyPlayer/MainPage.xaml.cs
  HyPlayer/Pages/BasePage.xaml
  HyPlayer/Pages/BasePage.xaml.cs
  HyPlayer/Pages/Me.xaml
  HyPlayer/Pages/Settings.xaml
  HyPlayer/Resources/Acrylic.xaml
  HyPlayer/Resources/Dark.xaml
  HyPlayer/Resources/Light.xaml
Labels: ~近期完成, =跟进中, @开发团队

#418 [feat] 逐字歌词使用 Win2D 实现
  HyPlayer/Classes/LyricRenderComposer.cs
  HyPlayer/Common.cs
  HyPlayer/Controls/LyricControl/LyricControl.Properties.cs
  HyPlayer/Controls/LyricControl/LyricControl.xaml
  HyPlayer/Controls/LyricControl/LyricControl.xaml.cs
  HyPlayer/Controls/LyricItem.xaml.cs
  HyPlayer/Controls/SongsList.xaml.cs
  HyPlayer/HyPlayControl/HyPlayList.cs
  HyPlayer/HyPlayer.csproj
  HyPlayer/Pages/CompactPlayerPage.xaml
  HyPlayer/Pages/CompactPlayerPage.xaml.cs
  HyPlayer/Pages/ExpandedPlayer.xaml.cs
  HyPlayer/Pages/Settings.xaml
Labels: · 增强, ~近期完成
